### ISSUE TITLE
Einträge werden doppelt Angezeigt

### ISSUE THREAD

**Issue by Kajakfrosch** [Kajakfrosch/Connect-HTML-Form-with-a-Database#12]
![image](https://user-images.githubusercontent.com/97800845/175898333-44939865-db47-4969-ab45-b67c63503bda.png)

die Nutzer werden mit jedem Spiel angezeigt 

@grumpyavner

**Comment by grumpyavner** [comment]
Sind da in der DB zwei Leute drin?

**Comment by Kajakfrosch** [comment]
wurde gefixt
